spring:
  profiles:
    active: dev

logging:
  config: classpath:config/log4j2.xml
  level:
    root: info

mybatis-plus:
  type-aliases-package: com.pighand.user.domain, com.pighand.user.vo
  type-handlers-package: com.pighand.framework.spring.type.handler
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

access-control-allow:
  mapping: "/**"
  origin: "*"
  methods: "*"
  headers: "*"

pighand:
  exception:
    intercept-exception: true

server:
  tcp:
    port: 2317

upload:
  path: /data/app/upload
  web-path: file

springdoc:
  enable-spring-security: false
  #  allow-circular-references: true
  # 设置api-docs
  api-docs:
    # 设置api-docs路径 默认: /v3/api-docs 如果开启了管理端口，那么这个也就失效了直接用/actuator/group-name代替
    path: /api-docs
    # 是否启用 默认: true
    enabled: true
    version: "openapi_3_0"

  #    swagger-ui配置 支持所有官方属性https://swagger.io/docs/open-source-tools/swagger-ui/usage/configuration/
  swagger-ui:
    path: /swagger-ui.html
    #    设置可以直接从应用根路径访问swagger-ui
    use-root-path: true